# Generated by Django 3.0.5 on 2021-05-26 17:13

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0002_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='reviews',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='RestApi.Review'),
        ),
    ]
