# Generated by Django 3.0.5 on 2021-05-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0003_auto_20210526_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='reviews',
        ),
    ]
