# Generated by Django 3.0.5 on 2021-05-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0008_dish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
